language: java
jdk:
- openjdk11
env:
  global:
    secure: mphAoAjtdmMbs6jXJFV8pOObVPBm50TilKWotL+vAQA+prZTL5XZzwHlI3ayYC864Ec0eArUHVwHHSlGeFDyGS3Y2Cl7NVVjVoIaUFqPX3yVdoTEtO2Kq575CCCL7kAiexCRu4lgkq/X+drRI9UR7AqFc1F/a1C0KWKX0vLNyJvnwWLYywhECEC0vjxH9OMCE4oT12R9e99oMuTMJVCiMfWtQyfeCgzdSVHGWu8RNF0/24Y4+jwTTZe2kqzxJY6wv6qTK0t9bfmomUyLPWr5y1q0+ikWtxwjqDtOtQv+uMSMlO638yVlDT/OK2SU3OCQ8XFMwqPEthTweP4znAcu/g12upWKj32HbIGEy1vBHOIc5DOp6UF9eAfN1VOG9kOXaExMv6aMaJX/lb4DtIYQ4gNmZlWKOUfy/c4pDXca3aH6YI6WLuFSfeWPSr8/tpyAp7j7hzXN/VUqIm+R36SmQ6DGdodHxsmH1ndYHkmXXx6/IuF0xkkE/0PYFzxbVcfZSqBGCGSWrg2f5ET8ym55sIiL3OLH7OHc1USPRHemsX1sh3Gh6mo4Ug1nH3rbcWIfoYDwxwVVo/HcTY8ms6jIeyaWNpkbkni049xhs5cr5alYmVuVIERc1/ZDh4W1dylGNoLab0nHCmDKQlQdKyWjW6a9k9yLm8rL+PQctYc1vP0=
